# Project Metadata
sonar.projectKey=flask-ebs
sonar.projectName=flask-ebs
sonar.projectVersion=1.0

# Source & Inclusions
sonar.sources=.
sonar.inclusions=app.py,config.py,models.py,templates/**

# Exclusions
# Exclude environment, database files, installer RPMs, bytecode, and deployment artifacts
sonar.exclusions=venv/**,.venv/**,**/__pycache__/**,**/*.pyc,app.db,*.rpm,Dockerfile,Jenkinsfile,Procfile

# Host Configuration
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
